model:
    arch: hardnet
data:
    dataset: base_cityscapes_convention
    version: scooter_halflabelled
    train_split: train
    val_split: val
    img_rows: 513
    img_cols: 513
    path: D:/perception_datasets/
    sbd_path: /mnt/ssd2/Cityscapes/
training:
    train_iters: 180000
    batch_size: 1
    val_interval: 100
    n_workers: 1
    print_interval: 10
    augmentations:
        hflip: 0.5
        rscale_crop: [1024, 1024]
    optimizer:
        name: 'sgd'
        lr: 0.002
        weight_decay: 0.0005
        momentum: 0.9
    loss:
        name: 'bootstrapped_cross_entropy'
        min_K: 4096
        loss_th: 0.3
        size_average: True
    lr_schedule: 
        name: 'poly_lr'
        max_iter: 180000
    resume: C:/Users/User/Desktop/fchardnet/weights/hardnet70_cityscapes_model.pkl
    finetune: None
validation:
    augmentations:
        gamma: 0.5 # < 1, controls shadows