model:
    arch: hardnet
    freeze: ['hardnet'] # portion of model to freeze: hardnet, bin_classifiers, classifiers
    bin_classifiers: # hidden layer configuration for each head, empty list means no hidden layer
        bus_stop:
            neurons: [512]
            dropouts: [0.5]
        junction:
            neurons: [512]
            dropouts: [0.5]
        road_break:
            neurons: [512]
            dropouts: [0.5]
        straight_pavement:
            neurons: [512]
            dropouts: [0.5]
data:
    dataset: base_cityscapes_convention
    version: detector
    train_split: train
    val_split: val
    img_rows: 513
    img_cols: 513
    path: D:/data/
    sbd_path: /mnt/ssd2/Cityscapes/
    bin_classifiers: # positive label for each binary classifier head
        bus_stop: ['bus_stop']
        junction: ['junction']
        road_break: ['road_break']
        straight_pavement: ['straight_pavement']
training:
    train_iters: 180000
    batch_size: 2
    val_interval: 20
    n_workers: 2
    print_interval: 10
    augmentations:
        hflip: 0.5
        rscale_crop: [1024, 1024]
    optimizer:
        name: 'sgd'
        lr: 0.002
        weight_decay: 0.0005
        momentum: 0.9
    loss:
        name: 'bootstrapped_cross_entropy'
        min_K: 4096
        loss_th: 0.3
        size_average: True
    bin_class_loss: # loss used for binary classifier head
        name: 'l1'
        weight: [[1.0], [1.0], [1.0], [1.0]] # 2D list, weight of each class for each head
    lr_schedule: 
        name: 'poly_lr'
        max_iter: 180000
    resume: D:/models/scooter_resized_halflabelled_180.pkl
    finetune: None    
