model:
    arch: hardnet
data:
    dataset: combined
    train_split: train
    val_split: val
    img_rows: 1024
    img_cols: 1024
    path: /home/whizz/Desktop/deeplabv3/datasets/
    sbd_path: /mnt/ssd2/Cityscapes/
training:
    train_iters: 120000
    batch_size: 8
    val_interval: 1000
    n_workers: 8
    print_interval: 10
    augmentations:
        hflip: 0.5
        rscale_crop: [1024, 1024]
    optimizer:
        name: 'sgd'
        lr: 0.02
        weight_decay: 0.0005
        momentum: 0.9
    loss:
        name: 'bootstrapped_cross_entropy'
        min_K: 4096
        loss_th: 0.3
        size_average: True
    lr_schedule: 
        name: 'poly_lr'
        max_iter: 120000
    resume: /home/whizz/Desktop/deeplabv3/FCHarDNet/runs/combined/cur/hardnet_combined_checkpoint.pkl
    finetune: None    
