model:
    arch: hardnet
data:
    dataset: softmax_direct_load
    version: scooter_halflabelled
    train_split: train
    val_split: val
    img_rows: 513
    img_cols: 513
    path: D:/data/
    sbd_path: /mnt/ssd2/Cityscapes/
training:
    train_iters: 180000
    batch_size: 2
    val_interval: 20
    n_workers: 2
    print_interval: 10
    augmentations:
    optimizer:
        name: 'sgd'
        lr: 0.002
        weight_decay: 0.0005
        momentum: 0.9
    loss:
        name: 'soft_and_hard_target_cross_entropy'
        temperature: 10
    lr_schedule: 
        name: 'poly_lr'
        max_iter: 180000
    resume: D:/repos/fchardnet/weights/hardnet70_cityscapes_model.pkl
    finetune: None    
